root = "."

tmp_dir = "tmp"

[build]
# Build command points to auth-service main.go
cmd = "go build -o tmp/auth-service ./services/auth-service/main.go"
bin = "tmp/auth-service"
include_ext = ["go", "mod", "sum", "env"]
exclude_dir = ["tmp", ".git"]
build_flags = "-v"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[watch]
# Watch all relevant directories
dirs = ["services/auth-service", "pkg", "libs/domain"]
extensions = ["go", "mod", "sum", "env"]
exclude_dirs = ["tmp", ".git"]
